countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antigua & Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bonaire, Sint Eustatius and Saba",
    "Bosnia Herzegovina",
    "Botswana",
    "Brazil",
    "British Virgin Islands",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Cook Islands",
    "Costa Rica",
    "Cote D'ivoire",
    "Croatia",
    "Curacao",
    "Cyprus",
    "Czech Republic",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "Vietnam",
    "Zambia",
    "Zimbabwe",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Faroe Islands",
    "Federated States of Micronesia",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong SAR, China",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iraq",
    "Ireland",
    "Isle Of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macau SAR, China",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "North Macedonia",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestinian Territory",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Republic of Congo",
    "Reunion Island",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Barthelemy",
    "Saint Kitts And Nevis",
    "Saint Lucia",
    "Saint Martin (France)",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten (Netherlands)",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "St. Vincent & Grenadines",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad & Tobago",
    "Tunisia",
    "Turkey",
    "Turks & Caicos Islands",
    "U.S. Virgin Islands",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
]

months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
]

month_dict = {
    "01": "January",
    "02": "February",
    "03": "March",
    "04": "April",
    "05": "May",
    "06": "June",
    "07": "July",
    "08": "August",
    "09": "September",
    "10": "October",
    "11": "November",
    "12": "December",
}

country_mapping = {
    "Continente y país de destino": "Continent and destination country",
    "Albania": "Albania",
    "Alemania": "Germany",
    "Andorra": "Andorra",
    "Armenia": "Armenia",
    "Austria": "Austria",
    "Belarús": "Belarus",
    "Bélgica": "Belgium",
    "Bosnia y Herzegovina": "Bosnia and Herzegovina",
    "Bulgaria": "Bulgaria",
    "Chipre": "Cyprus",
    "Croacia": "Croatia",
    "Dinamarca": "Denmark",
    "Eslovenia": "Slovenia",
    "Estonia": "Estonia",
    "Francia": "France",
    "Finlandia": "Finland",
    "Georgia": "Georgia",
    "Gibraltar": "Gibraltar",
    "Grecia": "Greece",
    "Hungría": "Hungary",
    "Irlanda": "Ireland",
    "Islandia": "Iceland",
    "Italia": "Italy",
    "Letonia": "Latvia",
    "Liechtenstein": "Liechtenstein",
    "Lituania": "Lithuania",
    "Luxemburgo": "Luxembourg",
    "Macedonia del Norte": "North Macedonia",
    "Malta": "Malta",
    "Moldavia": "Moldova",
    "Mónaco": "Monaco",
    "Montenegro": "Montenegro",
    "Noruega": "Norway",
    "Países Bajos": "Netherlands",
    "Polonia": "Poland",
    "Portugal": "Portugal",
    "Reino Unido": "United Kingdom",
    "República Checa": "Czech Republic",
    "República Eslovaca": "Slovakia",
    "Rumanía": "Romania",
    "Rusia": "Russia",
    "San Marino": "San Marino",
    "Santa Sede": "Holy See",
    "Serbia": "Serbia",
    "Suecia": "Sweden",
    "Suiza": "Switzerland",
    "Turquía": "Turkey",
    "Ucrania": "Ukraine",
    "Otros países o territorios de Europa": "Other countries or territories in Europe",
    "Unión Europea (sin España)": "European Union (excluding Spain)",
    "Angola": "Angola",
    "Argelia": "Algeria",
    "Benin": "Benin",
    "Botswana": "Botswana",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Cabo Verde": "Cape Verde",
    "Camerún": "Cameroon",
    "Chad": "Chad",
    "Comores": "Comoros",
    "Congo": "Congo",
    "Costa de Marfil": "Ivory Coast",
    "Djibouti": "Djibouti",
    "Egipto": "Egypt",
    "Eritrea": "Eritrea",
    "Etiopía": "Ethiopia",
    "Gabón": "Gabon",
    "Gambia": "Gambia",
    "Ghana": "Ghana",
    "Guinea": "Guinea",
    "Guinea-Bissau": "Guinea-Bissau",
    "Guinea Ecuatorial": "Equatorial Guinea",
    "Kenia": "Kenya",
    "Lesotho": "Lesotho",
    "Liberia": "Liberia",
    "Libia": "Libya",
    "Madagascar": "Madagascar",
    "Malawi": "Malawi",
    "Mali": "Mali",
    "Marruecos": "Morocco",
    "Mauricio": "Mauritius",
    "Mauritania": "Mauritania",
    "Mozambique": "Mozambique",
    "Namibia": "Namibia",
    "Níger": "Niger",
    "Nigeria": "Nigeria",
    "República Centroafricana": "Central African Republic",
    "República Democrática del Congo": "Democratic Republic of the Congo",
    "Ruanda": "Rwanda",
    "Santo Tomé y Príncipe": "São Tomé and Príncipe",
    "Senegal": "Senegal",
    "Seychelles": "Seychelles",
    "Sierra Leona": "Sierra Leone",
    "Somalia": "Somalia",
    "Sudáfrica": "South Africa",
    "Sudán": "Sudan",
    "Sudán del Sur": "South Sudan",
    "Swazilandia": "Eswatini",
    "Tanzania": "Tanzania",
    "Togo": "Togo",
    "Túnez": "Tunisia",
    "Uganda": "Uganda",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabwe",
    "Otros países o territorios de África": "Other countries or territories in Africa",
    # Continuing with American countries
    "América del Norte": "North America",
    "Centro América y Caribe": "Central America and the Caribbean",
    "Sudamérica": "South America",
    "Otros países o territorios de América": "Other countries or territories in America",
    # Adding Asian countries
    "Afganistán": "Afghanistan",
    "Arabia Saudí": "Saudi Arabia",
    "Azerbaiyán": "Azerbaijan",
    "Bahréin": "Bahrain",
    "Bangladesh": "Bangladesh",
    "Bhután": "Bhutan",
    "Brunei": "Brunei",
    "Camboya": "Cambodia",
    "China": "China",
    "Corea": "South Korea",
    "Corea del Norte": "North Korea",
    "Emiratos Árabes Unidos": "United Arab Emirates",
    "Filipinas": "Philippines",
    "India": "India",
    "Indonesia": "Indonesia",
    "Irán": "Iran",
    "Iraq": "Iraq",
    "Islas Marshall": "Marshall Islands",
    "Israel": "Israel",
    "Japón": "Japan",
    "Jordania": "Jordan",
    "Kazajstán": "Kazakhstan",
    "Kirguistán": "Kyrgyzstan",
    "Kuwait": "Kuwait",
    "Laos": "Laos",
    "Líbano": "Lebanon",
    "Malasia": "Malaysia",
    "Maldivas": "Maldives",
    "Mongolia": "Mongolia",
    "Myanmar": "Myanmar",
    "Nepal": "Nepal",
    "Omán": "Oman",
    "Pakistán": "Pakistan",
    "Palestina. Estado Observador, no miembro de Naciones Unidas": "Palestine. Observer State, not a United Nations member",
    "Qatar": "Qatar",
    "Singapur": "Singapore",
    "Siria": "Syria",
    "Sri Lanka": "Sri Lanka",
    "Tailandia": "Thailand",
    "Tayikistán": "Tajikistan",
    "Turkmenistán": "Turkmenistan",
    "Uzbekistán": "Uzbekistan",
    "Vietnam": "Vietnam",
    "Yemen": "Yemen",
    "Otros países o territorios de Asia": "Other countries or territories in Asia",
    # Adding Oceanian countries
    "Australia": "Australia",
    "Fiji": "Fiji",
    "Islas Cook": "Cook Islands",
    "Islas Salomón": "Solomon Islands",
    "Kiribati": "Kiribati",
    "Micronesia": "Micronesia",
    "Nauru": "Nauru",
    "Nueva Zelanda": "New Zealand",
    "Palaos": "Palau",
    "Papúa Nueva Guinea": "Papua New Guinea",
    "Samoa": "Samoa",
    "Timor Oriental": "East Timor",
    "Tonga": "Tonga",
    "Tuvalu": "Tuvalu",
    "Vanuatu": "Vanuatu",
    "Otros países o territorios de Oceanía": "Other countries or territories in Oceania",
}

tourism_concept_mapping = {
    "Concepto turístico": "Tourism concept",
    "Turistas": "Tourists",
    "Pernoctaciones": "Overnight stays",
    "Duración media de los viajes": "Average duration of trips",
}

translation_dict = {
    "Continent and destination country": "country",
    "Provincia": "province",
    "Tourism concept": "tourism_concept",
    "Periodo": "period",
    "Total": "total",
}
